[build]
  command = "python3 -m pip install mkdocs-material mkdocs-macros-plugin mkdocs-minify-plugin && python3 -m mkdocs build"
  publish = "site"

[build.environment]
  PYTHON_VERSION = "3.11"

[context.production]
  command = "python3 -m pip install mkdocs-material mkdocs-macros-plugin mkdocs-minify-plugin && python3 -m mkdocs build"

[context.branch-deploy]
  command = "python3 -m pip install mkdocs-material mkdocs-macros-plugin mkdocs-minify-plugin && python3 -m mkdocs build"

[context.deploy-preview]
  command = "python3 -m pip install mkdocs-material mkdocs-macros-plugin mkdocs-minify-plugin && python3 -m mkdocs build"
