# Generated by syda  |  model: claude-haiku-4-5-20251001  |  2026-06-08T01:47:51 UTC
# Edit freely — syda will use your changes on the next run.
# Columns with no generate_* function here are generated via LLM.

def generate_product_id(row, col_name):
    return row.name + 1

def generate_category(row, col_name):
    import random
    return random.choice(['Electronics', 'Clothing', 'Home & Garden', 'Sports & Outdoors', 'Books', 'Toys & Games'])

def generate_brand(row, col_name):
    import random
    import string
    brands = ['TechCorp', 'StyleMax', 'HomeElite', 'OutdoorPro', 'PageTurner', 'FunPlay', 'VisionTech', 'ComfortWear', 'GreenSpace', 'AdventureGear']
    return random.choice(brands)

def generate_price(row, col_name):
    import random
    return round(random.uniform(4.99, 999.99), 2)

def generate_stock_qty(row, col_name):
    import random
    return random.randint(0, 500)

def generate_product_name(row, col_name):
    import random
    adjectives = ['Premium', 'Deluxe', 'Professional', 'Advanced', 'Smart', 'Eco-Friendly', 'Ultra', 'Classic', 'Modern', 'Compact']
    nouns = ['Widget', 'Device', 'System', 'Tool', 'Pack', 'Set', 'Bundle', 'Collection', 'Gear', 'Essentials']
    words = [random.choice(adjectives), random.choice(nouns)]
    if random.random() > 0.5:
        descriptors = ['Pro', 'Max', 'Plus', 'Elite', 'Lite']
        words.append(random.choice(descriptors))
    name = ' '.join(words)
    return name[:80]
