#!/usr/bin/env python
"""
Example: force_llm column flag.

Demonstrates how force_llm: true in a schema YAML forces individual columns
to always be generated by the LLM — even in code-gen mode where the LLM
would normally write a Python function for them.

Schema: product catalog (600 rows → triggers code-gen mode automatically)
  - product_id, category, price, stock_qty  → code-gen (Python functions)
  - brand, product_name                     → LLM decides (likely code-gen)
  - tagline, description                    → force_llm: true → always LLM

The run report shows which strategy each column used, and the output CSV
contains rich AI-written taglines and descriptions alongside fast locally-
generated IDs, prices, and stock quantities.
"""

import os
import sys

from dotenv import load_dotenv

load_dotenv()
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from syda import SyntheticDataGenerator, ModelConfig

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "output")
SCHEMA_FILE = os.path.join(os.path.dirname(__file__), "schema_products.yml")
ROWS = 600  # >500 → code-gen mode kicks in automatically


def main():
    model_config = ModelConfig(
        provider="anthropic",
        model_name="claude-haiku-4-5-20251001",
    )

    generator = SyntheticDataGenerator(model_config=model_config)

    print("=" * 60)
    print("Generating product catalog with force_llm columns")
    print(f"  Rows        : {ROWS}")
    print(f"  Mode        : auto (>500 rows → code-gen)")
    print(f"  force_llm   : tagline, description")
    print(f"  Output dir  : {OUTPUT_DIR}")
    print("=" * 60)

    generator.generate_for_schemas(
        schemas={"products": SCHEMA_FILE},
        default_sample_size=ROWS,
        output_dir=OUTPUT_DIR,
    )

    # When output_dir is set, data is flushed to disk immediately and the
    # in-memory result is slimmed — read the CSV for display.
    import pandas as pd
    df = pd.read_csv(os.path.join(OUTPUT_DIR, "products.csv"))
    print(f"\n[OK] Generated {len(df)} products")

    # Show a sample of the force_llm columns to confirm rich LLM output
    print("\n── Sample taglines (force_llm) ──────────────────────────────")
    for i, row in df.head(3).iterrows():
        print(f"  [{row['category']}] {row['product_name']}")
        print(f"  Tagline    : {row['tagline']}")
        print(f"  Description: {row['description'][:120]}...")
        print()

    if generator.last_report:
        generator.last_report.print_summary()


if __name__ == "__main__":
    main()
